version: "3.8"

services:
  rocksdb-bench:
    image: ubuntu:24.04
    container_name: rocksdb-bench
    tty: true
    working_dir: /root
    volumes:
      - ../bench_rocksdb:/root/bench
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "/bin/bash"]

